[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cups",
  "libdrm",
  "dbus",
  "libxkbcommon",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib",
]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node server.js"
